// Generated by Wrangler by running `wrangler types`

interface Env {
	STOCK_KV: KVNamespace;
	MAX_NOTIFICATIONS: 3;
	TWILIO_ACCOUNT_SID: "xxx";
	TWILIO_AUTH_TOKEN: "xxx";
	TWILIO_PHONE_NUMBER: "xxx";
	TARGET_PHONE_NUMBER: "xxx";
}
